### ISSUE TITLE
Scanner Slip

### ISSUE THREAD

**Issue by Orcamm** [neural75/gqrx-scanner#4] opened 2018-12-12 11:05 UTC
When scanning three channels, I often find that though the scanner does detect the signal, it will cause the scanner to stop on the following channel. For example, the scanner will pick up a signal on channel 1 and then stop on channel two. This is the command I'm using. 

gqrx-scanner ./gqrx-scanner -m bookmark -t "Emergency" -d 7

I'm running it on my Manjaro arch install of linux with the command running non sudo in terminal. 

I am not a coder, but I suspect from seeing the issue it may be caused by the code not checking which channel the signal was detected on before halting the scan and going into delay. In other words the code may not be verifying the frequency of the signal which caused it to issue the halt command, so when a signal comes through near the end of the listen period the scanner can tend to slip off the desired frequency. 

Hopefully I have made my self understood. Great work on this, I use it much.

**Comment by neural75** [comment] 2018-12-12 21:06
I think the problem is that the db level read by gqrx is somewhat delayed during rapid change in frequency. This is tipical on the gqrx TCP api. Unfortunately the frequency has already changed when the level read finally reach the squelch threshold, stopping the scanner at the next freq (ghosts. I observe this during sweep mode and this is why I implemented a "fine tuning" returning on previous steps to locate the carrier better. In bookmark mode this is not implemented because the frequencies are fixed, but the delay on the incoming db measure is still there. I remember that I relaxed the parameters to avoid this problem in bookmark mode but perhaps It is not sufficient.  Too bad I did not expose an option to control the stabilization time before skip to the next freq (scan speed). However I will at the next release, hoping also to optimize the search algorithm to better fit the observed lag automatically.
Thank you for the report.
Neural

**Comment by Orcamm** [comment] 2018-12-13 00:05
Yes that sounds like the issue. Perhaps if the delay for the current scanning speed can be calculated then it's effects could be mitigated by referring the scanner to previous bookmark beyond a certain time period. I'm unsure, different sdr hardware may be different in this regard, assuming it is indeed an issue with gqrx and not with hardware timings. 

I'm using and RTL SDR dongle on my set up, although I've seen people using HackRF's and Nooelec's too. 

I suppose the best solution would be to first allow a parameter for how many milliseconds the scanner should move. I'll be happy to give it a test if you need some more information on the issue.

**Comment by stillline** [comment] 2019-01-12 06:16
I'm experiencing this same issue scanning 4 channels of the Los Angeles Fire Department. It seems to get a hit on channel 3 then stop on a digital frequency just above the bookmarked frequency. I love the program and I look forward to any updates. Thank for your work!

**Comment by t-geindre** [comment] 2019-03-25 12:47
Same issue here.
Any news ?
Thank you for your work by the way.

**Comment by Orcamm** [comment] 2019-03-25 12:53
@t-geindre I am not sure if the issue has been addressed. I have not used the scanner for sometime, however if the issue is corrected I'll be back for sure. From what I can understand it seems like it won't be that easy of a fix for a few reasons.

**Comment by drzraf** [comment] 2019-04-15 00:36
Same (blocking) issue here with Gqrx 2.9 in sweep mode.

**Comment by falsechicken** [comment] 2019-10-09 11:17
I also have an issue where it stops on an active channel but never resumes. I have two repeater frequencies set as my only two bookmarks. It finds an active frequency but doesn't continue the scan after.

**Comment by lwvmobile** [comment] 2020-04-30 16:36
@falsechicken This issue has been resolved in the latest update. The delay time constant was set to a value extremely high, so it had appeared to stop in the bookmark scan unless you specified a -d 3000 argument or similar. Now it should work and resume as intended after a 2.5 second delay on the bookmarked frequency.

@clumster @stillline @t-geindre This issue has been resolved (mostly) for the scanner slipping on the wrong frequency/bookmark by slowing down the scan rate from 85ms to 250 and also allowing you to specify a scan speed with the -x 300 to specify a custom scan speed in case its too fast , but be careful that the waterfall doesn't pan when starting the scan, if you are trying to bookmark scan on each fringes of the 2Mhz spectrum, you may still encounter issues where the adapter background noise changes cause a false positive if you observe the waterfall/spectrum shifting left to right and resetting. If you can keep it all close to the center and limit the frequency to a smaller sample then it should work fine. Here is a personal example that I use with good success.

./gqrx-scanner -m bookmark -x 250 -t "PFR" --min 154800000 --max 155400000

**Closed as completed** 2020-05-10 17:39 UTC
